Update dependencies
lenra-io/dev-tools pull request #157
Opened 2022-10-21 11:01 UTC by shiipou

feat: Upgrade lenra_ui_runner to v1.0.0-beta.91 feat: receive response from listeners (#191)

2022-10-26 13:09 UTC, jonas-martinez submitted a review, later dismissed

2022-10-28 14:38 UTC, taorepoara requested changes

2022-10-28 14:38 UTC, taorepoara commented on client/pubspec.lock
> -    version: "2.9.0"
It is downgrading the lock file...

2022-10-28 14:47 UTC, jonas-martinez commented on client/pubspec.lock
> -    version: "2.9.0"
@taorepoara Fixed

2022-11-01 13:02 UTC, shiipou commented
update lock

2022-11-29 15:53 UTC, shiipou commented
feat: Upgrade lenra_ui_runner to v1.0.0-beta.93

2022-12-20 13:40 UTC, shiipou commented
feat: Upgrade lenra_ui_runner to v1.0.0-beta.94

2022-12-20 13:46 UTC, shiipou commented
feat: Upgrade lenra_ui_runner to v1.0.0-beta.95

2022-12-20 14:18 UTC, shiipou commented
feat: Upgrade lenra_ui_runner to v1.0.0-beta.96

2022-12-26 16:00 UTC, shiipou commented
feat: Upgrade lenra_ui_runner to v1.0.0-beta.97

2022-12-27 08:47 UTC, closed without merging